# Generated by Django 4.2.4 on 2023-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('advisor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
            ],
        ),
    ]
