# Generated by Django 4.2.4 on 2023-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_requires_approval_subscriptionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(choices=[('Ciências Ambientais', 'Ciências Ambientais (Ecologia, Geologia, etc)'), ('Ciências da Saúde', 'Ciências da Saúde (Medicina, Biomedicina, etc)'), ('Ciências Exatas', 'Ciências Exatas (Matemática, Estatística, etc)'), ('Ciências Naturais', 'Ciências Naturais (Biologia, Química, Física, etc)'), ('Ciências Sociais', 'Ciências Sociais (Psicologia, Sociologia, etc)'), ('Engenharia', 'Engenharia (Elétrica, Mecânica, de Software, etc)'), ('Humanidades', 'Humanidades (História, Literatura, etc)'), ('Tecnologia da Informação', 'Tecnologia da Informação (IA, Segurança da Informação, etc)')], default='Ciências Exatas', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.CharField(choices=[('Curto Prazo', 'Curto Prazo: até 6 meses'), ('Médio Prazo', 'Médio Prazo: 6 a 12 meses'), ('Longo Prazo', 'Longo Prazo: mais de 12 meses')], default='Médio Prazo', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.CharField(max_length=100),
        ),
    ]
