# Generated by Django 4.2.4 on 2023-11-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_project_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="faculty",
        ),
        migrations.AddField(
            model_name="project",
            name="faculty",
            field=models.ManyToManyField(to="projects.faculty"),
        ),
    ]
