# Generated by Django 4.2.4 on 2023-11-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_faculty_sigla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="sigla",
            field=models.CharField(default="", max_length=20),
        ),
    ]
