# Generated by Django 3.2.23 on 2023-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20231122_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
