# Generated by Django 4.2.4 on 2023-10-05 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grande_area', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_area', models.CharField(blank=True, max_length=100, null=True)),
                ('bolsa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos_Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Perfil',
        ),
        migrations.CreateModel(
            name='ProjetoAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orientador', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.perfil')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='orientadorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.perfil'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pesquisador_associado_projetc',
            field=models.ManyToManyField(related_name='projetos_pesquisados', through='accounts.ProjetoAssociacao', to='accounts.perfil'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='requisito_orientado',
            field=models.ManyToManyField(to='accounts.requisitos_projeto'),
        ),
    ]
