# Generated by Django 4.2.4 on 2023-11-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="description",
        ),
    ]
