# Generated by Django 4.2.4 on 2023-11-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userprofile_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchproject",
            name="area",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="grade_area",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="sub_area",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="thesis",
        ),
        migrations.AddField(
            model_name="researchproject",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
