# Generated by Django 4.2.4 on 2023-11-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_researchproject_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="isTeacher",
            field=models.BooleanField(default=False),
        ),
    ]
