# Generated by Django 3.2.23 on 2023-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
