# Generated by Django 3.2.23 on 2023-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20231128_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default='Graduação', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='bolsa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pesquisador_associado_projetc',
            field=models.ManyToManyField(blank=True, null=True, related_name='projetos_pesquisados', through='accounts.ProjetoAssociacao', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='projetoassociacao',
            name='is_orientador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='requisitos_projeto',
            name='requisitos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
