name: CI

on:
  push:
    branches:
      - '**'  # ou o nome da sua branch padrão

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # ou a versão de Python que você está usando

      - name: Instalar dependências
        run: |
          pip install --no-deps -r requirements.txt

      - name: Executar testes
        run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              echo "python manage.py test accounts.tests --settings=conecta_cientifica.settings_test"
          done
